src/Entity/Cible.php
<?php

namespace App\Entity;

use App\Repository\CibleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CibleRepository::class)
 */
class Cible
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationality;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_name;

    /**
     * @ORM\ManyToOne(targetEntity=Mission::class, inversedBy="cibles", cascade = {"persist", "merge"})
     */
    private $mission;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getCodeName(): ?string
    {
        return $this->code_name;
    }

    public function setCodeName(string $code_name): self
    {
        $this->code_name = $code_name;

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->mission;
    }

    public function setMission(?Mission $mission): self
    {
        $this->mission = $mission;

        return $this;
    }
}

src/Form/CibleType.php
<?php

namespace App\Form;

use App\Entity\Cible;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class CibleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lastname')
            ->add('firstname')
            ->add('date_of_birth', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('nationality', ChoiceType::class, [
                'choices' => [
                    'Française' => 'Française',
                    'Anglaise' => 'Anglaise',
                    'Portugaise' => 'Portugaise',
                    'Espagnole' => 'Espagnole',
                    'Italienne' => 'Italienne',
                    'Allemande' => 'Allemande',
                    'Polonaise' => 'Polonaise',
                    'Belge' => 'Belge',
                    'Suisse' => 'Suisse',

                ]
            ])
            ->add('code_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cible::class,
        ]);
    }
}

src/Controller/CibleController.php
<?php

namespace App\Controller;

use App\Entity\Cible;
use App\Form\CibleType;
use App\Repository\CibleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/cible")
 */
class CibleController extends AbstractController
{
    /**
     * @Route("/", name="app_cible_index", methods={"GET"})
     */
    public function index(CibleRepository $cibleRepository): Response
    {
        return $this->render('cible/index.html.twig', [
            'cibles' => $cibleRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_cible_new", methods={"GET", "POST"})
     * @isGranted("ROLE_USER")
     */
    public function new(Request $request, CibleRepository $cibleRepository): Response
    {
        $cible = new Cible();
        $form = $this->createForm(CibleType::class, $cible);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cibleRepository->add($cible);
            return $this->redirectToRoute('app_cible_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cible/new.html.twig', [
            'cible' => $cible,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_cible_show", methods={"GET"})
     */
    public function show(Cible $cible): Response
    {
        return $this->render('cible/show.html.twig', [
            'cible' => $cible,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_cible_edit", methods={"GET", "POST"})
     * @isGranted("ROLE_USER")
     */
    public function edit(Request $request, Cible $cible, CibleRepository $cibleRepository): Response
    {
        $form = $this->createForm(CibleType::class, $cible);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cibleRepository->add($cible);
            return $this->redirectToRoute('app_cible_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cible/edit.html.twig', [
            'cible' => $cible,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_cible_delete", methods={"POST"})
     * @isGranted("ROLE_USER")
     */
    public function delete(Request $request, Cible $cible, CibleRepository $cibleRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cible->getId(), $request->request->get('_token'))) {
            $cibleRepository->remove($cible);
        }

        return $this->redirectToRoute('app_cible_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cible/_delete_form.html.twig
<form method="post" action="{{ path('app_cible_delete', {'id': cible.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer cette cible?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cible.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/cible/_form.html.twig
{{ form_start(form, {attr: {class: 'form-grid'}}) }}
    
    <div class="form-input-grid">
         <div class="form-input-text">
             {{ form_label(form.lastname, 'Nom: ') }}
         </div>
         {{ form_widget(form.lastname) }}
     </div>

     <div class="form-input-grid">
         <div class="form-input-text">
         {{ form_label(form.firstname, 'Prénom: ') }}
         </div>
         {{ form_widget(form.firstname) }}
     </div>

     <div class="form-input-grid">
         <div class="form-input-text">
         {{ form_label(form.date_of_birth, 'Date de naissance: ') }}
         </div>
         {{ form_widget(form.date_of_birth) }}
     </div>

     <div class="form-input-grid">
         <div class="form-input-text">
         {{ form_label(form.nationality, 'Nationalité: ') }}
         </div>
         {{ form_widget(form.nationality) }}
     </div>

     <div class="form-input-grid">
         <div class="form-input-text">
         {{ form_label(form.code_name, 'Nom de code: ') }}
         </div>
         {{ form_widget(form.code_name) }}
     </div>

    <div class="form-imput-agent">
        <button class="btn">{{ button_label|default('Enregistrer') }}</button>
    </div>

{{ form_end(form) }}

templates/cible/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Cible{% endblock %}

{% block body %}
    <h1 class="title">Modifier Cible</h1>

    {{ include('cible/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('app_cible_index') }}">Retour</a>

    {{ include('cible/_delete_form.html.twig') }}
{% endblock %}

templates/cible/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Cibles{% endblock %}

{% block body %}
    <h1 class="title">Liste des Cibles</h1>

    <button class="new-container">
    <a href="{{ path('app_cible_new') }}" class="new">Créer nouvelle</a>
    </button>

    <table class="table table-index-page">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Date de Naissance</th>
                <th>Nationalité</th>
                <th>Code</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cible in cibles %}
            <tr>
                <td>{{ cible.id }}</td>
                <td>{{ cible.lastname }}</td>
                <td>{{ cible.firstname }}</td>
                <td>{{ cible.dateOfBirth ? cible.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>{{ cible.nationality }}</td>
                <td>{{ cible.codeName }}</td>
                <td>
                    <a href="{{ path('app_cible_show', {'id': cible.id}) }}">Voir</a>
                    <a href="{{ path('app_cible_edit', {'id': cible.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">pas de résultat trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/cible/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Cible{% endblock %}

{% block body %}
    <h1 class="title">Créer nouvelle Cible</h1>

    {{ include('cible/_form.html.twig') }}

    <a href="{{ path('app_cible_index') }}">Retour</a>
{% endblock %}

templates/cible/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cible{% endblock %}

{% block body %}
    <h1 class="title-show-page">{{ cible.lastname }} {{ cible.firstname }}</h1>

    <table class="table table-show">
        <tbody>
            <tr>
                <th class="th-show">Id</th>
                <td>{{ cible.id }}</td>
            </tr>
            <tr>
                <th class="th-show">Nom</th>
                <td>{{ cible.lastname }}</td>
            </tr>
            <tr>
                <th class="th-show">Prénom</th>
                <td>{{ cible.firstname }}</td>
            </tr>
            <tr>
                <th class="th-show">Date de Naissance</th>
                <td>{{ cible.dateOfBirth ? cible.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th class="th-show">Nationalité</th>
                <td>{{ cible.nationality }}</td>
            </tr>
            <tr>
                <th class="th-show">Code</th>
                <td>{{ cible.codeName }}</td>
            </tr>
        </tbody>
    </table>

    <div class="show-actions">
        <a href="{{ path('app_cible_index') }}" class="show-retour">Retour</a>
        <a href="{{ path('app_cible_edit', {'id': cible.id}) }}" class="show-modifier">Modifier</a>
    </div>

    <div class="show-supprimer">
        {{ include('cible/_delete_form.html.twig') }}
    </div>

{% endblock %}