src/Entity/Agent.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AgentRepository")
 */
class Agent
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="date")
     */
    private $date_of_birth;

    /**
     * @ORM\Column(type="integer")
     */
    private $identification_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nationality;

    /**
     * @ORM\ManyToMany(targetEntity=Specialite::class, inversedBy="agents", cascade={"persist", "merge"})
     */
    private $specialite;

    /**
     * @ORM\ManyToOne(targetEntity=Mission::class, inversedBy="agents", cascade={"persist", "merge"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $mission;

    public function __construct()
    {
        $this->specialite = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }

    public function getIdentificationCode(): ?int
    {
        return $this->identification_code;
    }

    public function setIdentificationCode(int $identification_code): self
    {
        $this->identification_code = $identification_code;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    /**
     * @return Collection<int, Specialite>
     */
    public function getSpecialite(): Collection
    {
        return $this->specialite;
    }

    public function addSpecialite(Specialite $specialite): self
    {
        if (!$this->specialite->contains($specialite)) {
            $this->specialite[] = $specialite;
        }

        return $this;
    }

    public function removeSpecialite(Specialite $specialite): self
    {
        $this->specialite->removeElement($specialite);

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->mission;
    }

    public function setMission(?Mission $mission): self
    {
        $this->mission = $mission;

        return $this;
    }
}

src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MissionRepository")
 */
class Mission
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date;

    /**
     * @ORM\OneToMany(targetEntity=Agent::class, mappedBy="mission", cascade={"persist", "merge"})
     */
    private $agents;

    /**
     * @ORM\OneToMany(targetEntity=Cible::class, mappedBy="mission", cascade={"persist", "merge"})
     */
    private $cibles;

    /**
     * @ORM\OneToMany(targetEntity=Contact::class, mappedBy="mission", cascade={"persist", "merge"})
     */
    private $contacts;

    /**
     * @ORM\OneToMany(targetEntity=Planque::class, mappedBy="mission", cascade={"persist", "merge"})
     */
    private $planques;

    /**
     * @ORM\ManyToOne(targetEntity=Specialite::class, inversedBy="missions", cascade={"persist", "merge"})
     */
    private $speciality;

    /**
     * @ORM\ManyToOne(targetEntity=Status::class, inversedBy="missions", cascade={"persist", "merge"})
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=TypeMission::class, inversedBy="missions", cascade={"persist", "merge"})
     */
    private $type;

    public function __construct()
    {
        $this->agents = new ArrayCollection();
        $this->cibles = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->planques = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCodeName(): ?string
    {
        return $this->code_name;
    }

    public function setCodeName(string $code_name): self
    {
        $this->code_name = $code_name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    /**
     * @return Collection<int, Agent>
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents[] = $agent;
            $agent->setMission($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getMission() === $this) {
                $agent->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cible>
     */
    public function getCibles(): Collection
    {
        return $this->cibles;
    }

    public function addCible(Cible $cible): self
    {
        if (!$this->cibles->contains($cible)) {
            $this->cibles[] = $cible;
            $cible->setMission($this);
        }

        return $this;
    }

    public function removeCible(Cible $cible): self
    {
        if ($this->cibles->removeElement($cible)) {
            // set the owning side to null (unless already changed)
            if ($cible->getMission() === $this) {
                $cible->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setMission($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getMission() === $this) {
                $contact->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Planque>
     */
    public function getPlanques(): Collection
    {
        return $this->planques;
    }

    public function addPlanque(Planque $planque): self
    {
        if (!$this->planques->contains($planque)) {
            $this->planques[] = $planque;
            $planque->setMission($this);
        }

        return $this;
    }

    public function removePlanque(Planque $planque): self
    {
        if ($this->planques->removeElement($planque)) {
            // set the owning side to null (unless already changed)
            if ($planque->getMission() === $this) {
                $planque->setMission(null);
            }
        }

        return $this;
    }

    public function getSpeciality(): ?Specialite
    {
        return $this->speciality;
    }

    public function setSpeciality(?Specialite $speciality): self
    {
        $this->speciality = $speciality;

        return $this;
    }

    public function getStatus(): ?Status
    {
        return $this->status;
    }

    public function setStatus(?Status $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getType(): ?TypeMission
    {
        return $this->type;
    }

    public function setType(?TypeMission $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function __toString()
    {
        return $this->country;
    }

}

src/Form/MissionType.php
<?php

namespace App\Form;

use App\Entity\Agent;
use App\Entity\Cible;
use App\Entity\Contact;
use App\Entity\Mission;
use App\Entity\Planque;
use App\Entity\Specialite;
use App\Entity\Status;
use App\Entity\TypeMission;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('code_name')
            ->add('country', ChoiceType::class, [
                'choices' => [
                    'France' => 'France',
                    'Angleterre' => 'Angleterre',
                    'Suisse' => 'Suisse',
                    'Allemagne' => 'Allemagne',
                    'Espagne' => 'Espagne',
                    'Portugal' => 'Portugal',
                    'Italie' => 'Italie',
                    'Belgique' => 'Belgique',
                    'Pologne' => 'Pologne',
                ]
            ])
            ->add('speciality', EntityType::class, [
                'label' => 'Choisir une spécialité: ',
                'placeholder' => 'Choisir une spécialité',
                'class' => Specialite::class,
                'choice_label' => 'name'
            ])
            ->add('agents', EntityType::class, [
                'label' => 'Choisir un ou des agent(s): ',
                'class' => Agent::class,
                'choice_label' => 'identification_code',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('contacts', EntityType::class, [
                'label' => 'Selectionner le(les) contact(s): ',
                'class' => Contact::class,
                'choice_label' => 'code_name',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('cibles', EntityType::class, [
                'label' => 'Selectionner la(les) cible(s): ',
                'class' => Cible::class,
                'choice_label' => 'code_name',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('planques', EntityType::class, [
                'label' => 'Selectionner la(les) planque(s): ',
                'class' => Planque::class,
                'choice_label' => 'code',
                'multiple' => true,
                'expanded' => true,
            ])
            ->add('start_date', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('end_date', DateType::class, [
                'widget' => 'single_text'
            ])
            ->add('status', EntityType::class, [
                'label' => 'Statut de la Mission: ',
                'class' => Status::class,
                'choice_label' => 'name'
            ])
            ->add('type', EntityType::class, [
                'label' => 'Type de Mission: ',
                'class' => TypeMission::class,
                'choice_label' => 'name'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Mission::class,
        ]);
    }
}

src/Controller/MissionController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Form\MissionType;
use App\Data\SearchData;
use App\Form\SearchForm;
use App\Repository\MissionRepository;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/mission")
 */
class MissionController extends AbstractController
{
    /**
     * @Route("/", name="app_mission_index", methods={"GET"})
     */
    public function index(MissionRepository $repository, Request $request): Response
    {
        $data = new SearchData();
        $form = $this->createForm(SearchForm::class, $data);
        $form->handleRequest($request);
        $missions = $repository->findSearch($data);
        if($request->get('ajax')) {
            return new JsonResponse([
                'content' => $this->renderView('mission/_list.html.twig', ['missions' => $missions])
            ]);
        }
        return $this->render('mission/index.html.twig', [
            'missions' => $missions,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/new", name="app_mission_new", methods={"GET", "POST"})
     * @isGranted("ROLE_USER")
     */
    public function new(Request $request, MissionRepository $missionRepository): Response
    {
        $mission = new Mission();
        $form = $this->createForm(MissionType::class, $mission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionRepository->add($mission);
        
           
            return $this->redirectToRoute('app_mission_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mission/new.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_mission_show", methods={"GET"})
     */
    public function show(Mission $mission): Response
    {
        return $this->render('mission/show.html.twig', [
            'mission' => $mission,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_mission_edit", methods={"GET", "POST"})
     * @isGranted("ROLE_USER")
     */
    public function edit(Request $request, Mission $mission, MissionRepository $missionRepository): Response
    {
        $form = $this->createForm(MissionType::class, $mission);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $missionRepository->add($mission);

            return $this->redirectToRoute('app_mission_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('mission/edit.html.twig', [
            'mission' => $mission,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_mission_delete", methods={"POST"})
     * @isGranted("ROLE_USER")
     */
    public function delete(Request $request, Mission $mission, MissionRepository $missionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$mission->getId(), $request->request->get('_token'))) {
            $missionRepository->remove($mission);
        }

        return $this->redirectToRoute('app_mission_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/mission/_delete_form.html.twig
<form method="post" action="{{ path('app_mission_delete', {'id': mission.id}) }}" onsubmit="return confirm('Êtes-vous sûre de vouloir supprimer cette mission?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/mission/_form.html.twig
{{ form_start(form) }}

    <div class="form-ligne-1">

        <div class="form-input">
            <div class="form-input-text">
                {{ form_label(form.title, 'Titre') }}
            </div>
            {{ form_widget(form.title) }}
        </div>

        <div class="form-input">
            <div class="form-input-text description">
            {{ form_label(form.description, 'Description') }}
            </div>
            {{ form_widget(form.description) }}
        </div>

        <div class="form-input">
            <div class="form-input-text">
                {{ form_label(form.country, 'Pays') }}
            </div>
            {{ form_widget(form.country) }}
        </div>

        <div class="form-input">
            <div class="form-input-text">
                {{ form_label(form.code_name, 'Nom de code') }}
            </div>
            {{ form_widget(form.code_name) }}
        </div>

    </div>

    <div class="form-container">
        {{ form_row(form.speciality, {attr: {class: 'form-list'}}) }}
    </div>

    <div class="form-container">
        {{ form_row(form.agents, {attr: {class: 'form-checkbox'}}) }}
    </div>

    <div class="form-container">
        {{ form_row(form.contacts, {attr: {class: 'form-checkbox'}}) }}
    </div>

    <div class="form-container">
        {{ form_row(form.cibles, {attr: {class: 'form-checkbox'}}) }}
    </div>

    <div class="form-container">
        {{ form_row(form.planques, {attr: {class: 'form-checkbox'}}) }}
    </div>

    <div class="form-container">
        {{ form_label(form.start_date, 'Date de début: ') }}
        {{ form_widget(form.start_date, {attr: {class: 'form-date'}}) }}
    </div>

    <div class="form-container">
        {{ form_label(form.end_date, 'Date de fin: ') }}
        {{ form_widget(form.end_date, {attr: {class: 'form-date'}}) }}
    </div>

    <div class="form-container">
        {{ form_row(form.status, {attr: {class: 'form-list'}}) }}
    </div>

    <div class="form-container">
        {{ form_row(form.type, {attr: {class: 'form-list'}}) }}
    </div>

    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/mission/_list.html.twig
<table class="table">

         {% if is_granted('ROLE_USER') %}
             <button class="new-container-mission">
                 <a href="{{ path('app_mission_new') }}" class="new">Créer nouvelle</a>
            </button>
         {% endif %}
    <thead class="titre-colonne">
        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Description</th>
            <th>Nom de Code</th>
            <th>Pays</th>
            <th>Specialité</th>
            <th>Action(s)</th>
        </tr>
    </thead>
    <tbody>
        {% for mission in missions %}
            <tr>
                <td>{{ mission.id }}</td>
                <td>{{ mission.title }}</td>
                <td>{{ mission.description }}</td>
                <td>{{ mission.codeName }}</td>
                <td>{{ mission.country }}</td>
                 <td>{% if mission.speciality %}
                    {{ mission.speciality.name }} 
                    {% endif %}
                </td>
                <td>
                    <a href="{{ path('app_mission_show', {'id': mission.id}) }}">Voir</a>
                    {% if is_granted('ROLE_USER') %}
                    <a href="{{ path('app_mission_edit', {'id': mission.id}) }}">Modifier</a>
                    {% endif %}
                </td>
            </tr> 
        {% else %}
            <tr>
                <td colspan="9">pas de résultat trouvé</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

templates/mission/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Mission{% endblock %}

{% block body %}
    <h1 class="title">Modifier Mission</h1>

    {{ include('mission/_form.html.twig', {'button_label': 'Enregistrer'}) }}

    <a href="{{ path('app_mission_index') }}">Retour</a>

{% endblock %}

templates/mission/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Liste Missions{% endblock %}

{% block body %}
    <h1 class="title">Liste des Missions</h1>
    
    <div class="js-filter">

        <div class="search">
        {% include 'search/search.html.twig' %}
        </div>

        <div class="main">
            <div class="number-mission">
                <span>Nombre de missions :<span>
                {{ missions|length }}

            </div>
             <div class="js-filter-content">
                {% include 'mission/_list.html.twig' %}
             </div>
        </div>

    </div>

{% endblock %}

templates/mission/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Mission{% endblock %}

{% block body %}
    <h1 class="title">Créer une nouvelle mission</h1>

    {{ include('mission/_form.html.twig') }}

    <a href="{{ path('app_mission_index') }}">Retour</a>
{% endblock %}

templates/mission/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mission{% endblock %}

{% block body %}
    <h1 class="title">{{ mission.title }}</h1>

    <table class="table table-show">
        <tbody>
            <tr>
                <th class="th-show">Id</th>
                <td>{{ mission.id }}</td>
            </tr>
            <tr>
                <th class="th-show">Titre</th>
                <td>{{ mission.title }}</td>
            </tr>
            <tr>
                <th class="th-show">Description</th>
                <td>{{ mission.description }}</td>
            </tr>
            <tr>
                <th class="th-show">Nom de Code</th>
                <td>{{ mission.codeName }}</td>
            </tr>
            <tr>
                <th class="th-show">Pays</th>
                <td>{{ mission.country }}</td>
            </tr>
            <tr>
                <th class="th-show">Specialité</th>
                <td>{% if mission.speciality %}
                    {{ mission.speciality.name }} 
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="th-show">Agent(s)</th>
                <td>{% for agents in mission.agents %}
                    {{ agents.identificationCode }}
                    {% endfor %}</td>
            </tr>
             <tr>
                <th class="th-show">Contact(s)</th>
                <td>{% for contacts in mission.contacts %}
                    {{ contacts.codeName }}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th class="th-show">Cible(s)</th>
                <td>{% for cibles in mission.cibles %}
                    {{ cibles.codeName }}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th class="th-show">Planque(s)</th>
                <td>{% for planques in mission.planques %}
                    {{ planques.code }}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th class="th-show">Date Début</th>
                <td>{{ mission.startDate ? mission.startDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th class="th-show">Date Fin</th>
                <td>{{ mission.endDate ? mission.endDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th class="th-show">Statut</th>
                <td>{% if mission.status %}
                    {{ mission.status.name }} 
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th class="th-show">Type</th>
                 <td>{% if mission.type %}
                    {{ mission.type.name }} 
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
    
    <div class="show-actions">
        <a href="{{ path('app_mission_index') }}" class="show-retour">Retour</a>
        <a href="{{ path('app_mission_edit', {'id': mission.id}) }}" class="show-modifier">Modifier</a>
    </div>

{% endblock %}